"""Add brief_description to DrugResult

Revision ID: 348e80950c2f
Revises: 77a733438732
Create Date: 2025-09-01 22:20:24.564651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '348e80950c2f'
down_revision = '77a733438732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drug_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brief_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drug_result', schema=None) as batch_op:
        batch_op.drop_column('brief_description')

    # ### end Alembic commands ###
