"""Remove unused fields from DrugResult

Revision ID: 57f7ddf30e48
Revises: 348e80950c2f
Create Date: 2025-09-01 23:07:49.228693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57f7ddf30e48'
down_revision = '348e80950c2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drug_result', schema=None) as batch_op:
        batch_op.drop_column('parsed_frequency')
        batch_op.drop_column('parsed_dosage')
        batch_op.drop_column('fda_status')
        batch_op.drop_column('normalized_route')
        batch_op.drop_column('parsed_units')
        batch_op.drop_column('ema_status')
        batch_op.drop_column('who_eml_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drug_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('who_eml_status', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('ema_status', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('parsed_units', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('normalized_route', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('fda_status', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('parsed_dosage', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('parsed_frequency', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
