"""Initial migration.

Revision ID: 77a733438732
Revises:
Create Date: 2025-09-01 21:38:09.755966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a733438732'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('upload_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drug_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('inn_protocol', sa.String(length=255), nullable=True),
    sa.Column('usage_protocol', sa.Text(), nullable=True),
    sa.Column('loe_protocol', sa.String(length=50), nullable=True),
    sa.Column('inn_english', sa.String(length=255), nullable=True),
    sa.Column('parsed_dosage', sa.String(length=50), nullable=True),
    sa.Column('parsed_units', sa.String(length=50), nullable=True),
    sa.Column('parsed_frequency', sa.String(length=100), nullable=True),
    sa.Column('normalized_route', sa.String(length=100), nullable=True),
    sa.Column('who_eml_status', sa.String(length=50), nullable=True),
    sa.Column('fda_status', sa.String(length=50), nullable=True),
    sa.Column('ema_status', sa.String(length=50), nullable=True),
    sa.Column('pubmed_links', sa.Text(), nullable=True),
    sa.Column('system_loe', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drug_result')
    op.drop_table('analysis')
    # ### end Alembic commands ###
